inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'Guardfile'
    - 'Rakefile'
    - 'README.md'
    - 'node_modules/**/*'

  DisplayCopNames: true

Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Include:
    - 'app/controllers/*'
    - 'app/models/*'
  Max: 20
Metrics/AbcSize:
  Include:
    - 'app/controllers/*'
    - 'app/models/*'
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  ExcludeMethods: ['describe']
  Max: 30
  Exclude:
    - config/**/*
    - spec/**/*
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/HashAlignment:
  EnforceColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforceStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - spec/features/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/*
